### ISSUE TITLE
Download file name construction for newer z3 releases.

### ISSUE THREAD

**Issue by philderbeast** [pavpanchekha/setup-z3#7]
Thanks for this action. I've been contributing to some of the Liquid Haskell repos and this action is in use there.

```yaml
      - name: Setup z3
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: "4.8.7"
```

It looks like file name construction won't work for some of the newer releases of the z3 solver.

https://github.com/pavpanchekha/setup-z3/blob/77c3359e5f24bf445e32c97eafddb2ab104b8b8e/index.js#L5-L6

![Screen Shot 2022-08-02 at 7 16 50 AM](https://user-images.githubusercontent.com/633283/182362157-94bfd46e-c5e3-4831-8114-cdd4b399773e.png)

The `z3-4.8.17` binaries:

![Screen Shot 2022-08-02 at 9 22 32 AM](https://user-images.githubusercontent.com/633283/182385189-f99b5131-7ad5-4afd-a28c-67e020cf31ea.png)

The `z3-4.10.2` binaries:

![Screen Shot 2022-08-02 at 9 20 35 AM](https://user-images.githubusercontent.com/633283/182384845-07942c65-b9fc-48f8-957a-e381a17c272d.png)

**Comment by pavpanchekha** [comment]
Ugh. This happens every now and then. I'm happy to accept a PR; otherwise I'll fix it as I have time, which I can't give a SLA on.

**Comment by pavpanchekha** [comment]
Just to make sure I have the issue right, is the problem just that the default `distribution` is now incorrect, and should be changed to `glibc-2.31`? I've done that, please let me know if it worked.

**Comment by philderbeast** [comment]
Thanks @pavpanchekha.

6b2d476d7a9227e0d8d2b94f73cd9fcba91b5e98 works for installing `z3-4.10.2` but not for installing `z3-4.8.7`. With a conditional I can install either version.

```yaml
jobs:
  build:
    name: z3-${{ matrix.z3 }}
    runs-on: ubuntu-latest
    strategy:
        z3:
          - "4.8.7"
          - "4.10.2"
 
    steps:
      - name: Setup z3-4.8.7
        if: ${{ matrix.z3 == '4.8.7' }}
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: ${{ matrix.z3 }}

      - name: Setup z3-4.10.2
        if: ${{ matrix.z3 == '4.10.2' }}
        uses: pavpanchekha/setup-z3@6b2d476d7a9227e0d8d2b94f73cd9fcba91b5e98
        with:
          version: ${{ matrix.z3 }}
```

**Comment by philderbeast** [comment]
This is another way of getting `z3-4.8.7`:

```yaml
      - name: Setup z3-4.8.7
        if: ${{ matrix.z3 == '4.8.7' }}
        uses: pavpanchekha/setup-z3@6b2d476d7a9227e0d8d2b94f73cd9fcba91b5e98
        with:
          version: ${{ matrix.z3 }}
          distribution: ubuntu-16.04
```
